version: '3'

services:
  lb:
    build: 
      context: .
      dockerfile: Dockerfile
    image: kholif/lb-pay
    container_name: loopb
    restart: always
    env_file: .env
    environment:
      - PORT=$PORT
      - NODE_ENV=NODE_ENV
      - PAYMENT_SECRET=$PAYMENT_SECRET 
      - SID=$SID
    ports:
      - "3000:3000"
    volumes:
      - .:/home/lb/app
      - node_modules:/home/lb/app/node_modules
    networks:
      - lb-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js 
    # depends_on:
    #   - db
    links:
      - db
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    # restart: always
    # env_file: .env
    volumes:     
      - dbdata:/var/lib/mongodb
    networks:
      - lb-network  
    # ports:
    #   - "27017:27017"

networks:
  lb-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  